# Jekyll Resume Theme

# Site settings
title: Jonas Haag
email: jonas.haag@hotmail.com
description: Jonas Haag Portfolio
baseurl: "portfolio"
url: ""
name: Jonas Haag
job:  iOS & Android Developer
location: Lund, Sweden
languages: Swift, Java and cats
github_username:  wanaka
email_address: jonas.haag@hotmail.com

# Build settings
markdown: kramdown

# deployment
host: 0.0.0.0
port: 5000